### ISSUE TITLE
questions about class-specific margins

### ISSUE THREAD

**Issue by YongZh958** [Phoenix-V/DiGeo#5]
大佬，你好，你们实验室非常的厉害，发表了如fct，meta faster rcnn，十分佩服。关于论文中
![image](https://github.com/Phoenix-V/DiGeo/assets/75669193/56857378-ce12-4621-80ae-e320ae1f1163)

“where pc is the frequency of bounding box annotations for class c, and p− is an estimated probability of background boxes to train the classifier, and p− + ∑ c∈Cb∪Cn pc = 1”，
pc是类别c的频率，那对Pc求和的结果不就是1吗，为什么p-＋Σpc=1，是我对pc和p-的理解那个部分有问题吗？

**Comment by Phoenix-V** [comment]
您好，感谢您的关注，这个地方的分类是N+1，这里的“N”是全部foreground class的数量，然后“+1”是因为还有一个background class
